services:
  postgres:
    user: root
    image: postgres
    container_name: guild-master_postgres
    ports:
      - 6500:5432
    env_file:
      - ./.env
    volumes:
      - postgres:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: guild-master_pgadmin
    depends_on:
      - postgres
    ports:
      - 5050:80
    env_file:
      - ./.env
    volumes:
      - pgadmin:/var/lib/pgadmin
volumes:
  postgres:
  pgadmin: