export const JobSpecialties = new Map<string, string[]>();
JobSpecialties.set("Guild Coach", ["Wizard Expert", "Barbarian Expert", "Bard Expert", "Cleric Expert", "Druid Expert", "Fighter Expert", "Monk Expert", "Paladin Expert", "Ranger Expert", "Rouge Expert", "Sorcerer Expert", "Warlock Expert"]);
JobSpecialties.set("Assistant Coach", ["Strength", "Magic", "Defense", "Dexterity", "Resistance", "Constitution"]);
JobSpecialties.set("Butler", ["Tidy", "People Person"]);
JobSpecialties.set("Grounds Keeper", ["Tidy", "Equipment Pro"]);
JobSpecialties.set("Chef", ["Str+", "Mag+", "Def+", "Dex+", "Res+", "Con+"]);
JobSpecialties.set("Vendor", ["Meat", "Ale", "Cheese", "Bread", "Wine"]);
JobSpecialties.set("Healer", ["Quick Hands", "Efficient", "Caretaker"]);
JobSpecialties.set("Arena Manager", ["Fan First", "Entertainer"]);
JobSpecialties.set("Guild Scout", ["Wizard Expert", "Barbarian Expert", "Bard Expert", "Cleric Expert", "Druid Expert", "Fighter Expert", "Monk Expert", "Paladin Expert", "Ranger Expert", "Rouge Expert", "Sorcerer Expert", "Warlock Expert"]);